[package]
name = "touying-pres-bit"
version = "0.1.0"
entrypoint = "theme.typ"
authors = ["Quaternijkon<https://github.com/Quaternijkon>"]
license = "MIT"
description = "Touying Slide Theme for BIT"
repository = "https://github.com/Quaternijkon/Typst_USTC_CS"
keywords = ["touying", "slide", "presentation", "BIT", "university"]
categories = ["presentation"]
exclude = ["main.pdf"]

[template]
path = "content/example"
entrypoint = "main.typ"
thumbnail = "image.png"
